export const appOptions = [
  { id: 'tiktok', name: 'TikTok', category: 'Short video', glyph: 'Tk', logo: 'tiktok', tone: '#111827', returnShortcut: 'LoopOut Return TikTok' },
  { id: 'instagram', name: 'Instagram', category: 'Social', glyph: 'Ig', logo: 'instagram', tone: '#F0447A', returnShortcut: 'LoopOut Return Instagram' },
  { id: 'youtube', name: 'YouTube Shorts', category: 'Short video', glyph: 'Yt', logo: 'youtube', tone: '#FF2D2D', returnShortcut: 'LoopOut Return YouTube' },
  { id: 'snapchat', name: 'Snapchat', category: 'Messaging', glyph: 'Sc', logo: 'snapchat', tone: '#FACC15', returnShortcut: 'LoopOut Return Snapchat' },
  { id: 'x', name: 'X', category: 'News feed', glyph: 'X', logo: 'x', tone: '#0B1220', returnShortcut: 'LoopOut Return X' },
  { id: 'netflix', name: 'Netflix', category: 'Streaming', glyph: 'Nf', logo: 'netflix', tone: '#E50914' },
  { id: 'discord', name: 'Discord', category: 'Community', glyph: 'Dc', logo: 'discord', tone: '#5865F2' },
  { id: 'games', name: 'Games', category: 'Entertainment', glyph: 'Gm', logo: 'games', tone: '#22C55E' },
  { id: 'custom', name: 'Custom app', category: 'Your choice', glyph: '+', logo: 'custom', tone: '#3C76F9' },
];

export const quickTimers = [5, 10, 15, 20];
export const lockDurations = [30, 45, 60];

export const onboardingSlides = [
  {
    title: 'Use your apps with intention.',
    text: "Before opening a distracting app, LoopOut asks why you're opening it.",
  },
  {
    title: 'Set a clear limit.',
    text: 'Choose how long you want to use the app before the timer starts.',
  },
  {
    title: 'Go offline together.',
    text: 'When your time ends, see which friends are also offline and meet in phone-free places.',
  },
  {
    title: 'Connect with iPhone Automations.',
    text: 'Use Shortcuts to open LoopOut whenever you open distracting apps.',
  },
];

export const lisbonPlaces = [
  {
    id: 'galveias',
    name: 'Biblioteca Palacio Galveias',
    type: 'Libraries',
    area: 'Campo Pequeno',
    description: 'A quiet library for focused study, reading and reset time.',
    activity: 'Study or read',
    suggestion: 'Put phones face down for 45 minutes.',
    score: 5,
    coordinates: { lat: 38.7409, lng: -9.1446 },
  },
  {
    id: 'marvila',
    name: 'Biblioteca de Marvila',
    type: 'Libraries',
    area: 'Marvila',
    description: 'A generous study space with calm corners for group focus.',
    activity: 'Study together',
    suggestion: 'Use this as a quiet focus zone.',
    score: 4,
    coordinates: { lat: 38.746, lng: -9.1052 },
  },
  {
    id: 'alcantara',
    name: 'Biblioteca de Alcantara',
    type: 'Libraries',
    area: 'Alcantara',
    description: 'A practical meeting point for project work and reading.',
    activity: 'Study or project work',
    suggestion: 'Meet for a distraction-free work session.',
    score: 4,
    coordinates: { lat: 38.7057, lng: -9.1788 },
  },
  {
    id: 'gulbenkian',
    name: 'Fundacao Calouste Gulbenkian Gardens',
    type: 'Parks & gardens',
    area: 'Praca de Espanha / Sao Sebastiao',
    description: 'A peaceful garden loop for short walks and deeper talks.',
    activity: 'Walk and talk',
    suggestion: 'Go for a 30-minute walk without phones.',
    score: 5,
    coordinates: { lat: 38.737, lng: -9.1543 },
  },
  {
    id: 'estrela',
    name: 'Jardim da Estrela',
    type: 'Public gardens',
    area: 'Estrela',
    description: 'A relaxed outdoor place to meet friends after class.',
    activity: 'Meet friends',
    suggestion: 'Talk, walk, sit outside.',
    score: 4,
    coordinates: { lat: 38.7138, lng: -9.1604 },
  },
  {
    id: 'botanico',
    name: 'Jardim Botanico de Lisboa',
    type: 'Public gardens',
    area: 'Principe Real / Rato',
    description: 'A leafy, slow-paced garden that naturally invites quiet conversation.',
    activity: 'Walk and reset',
    suggestion: 'Keep phones in bags until you leave the garden.',
    score: 5,
    coordinates: { lat: 38.7182, lng: -9.1485 },
  },
  {
    id: 'torel',
    name: 'Jardim do Torel',
    type: 'Public gardens',
    area: 'Santana / Avenida',
    description: 'A calm city garden with views, benches and room to pause.',
    activity: 'Viewpoint talk',
    suggestion: 'Meet for 25 minutes without checking notifications.',
    score: 4,
    coordinates: { lat: 38.7203, lng: -9.1383 },
  },
  {
    id: 'cerca-graca',
    name: 'Jardim da Cerca da Graca',
    type: 'Public gardens',
    area: 'Graca',
    description: 'A spacious hillside garden for low-pressure walks and fresh air.',
    activity: 'Walk and talk',
    suggestion: 'Use the walk as the timer instead of your phone.',
    score: 5,
    coordinates: { lat: 38.7178, lng: -9.1301 },
  },
  {
    id: 'necessidades',
    name: 'Tapada das Necessidades',
    type: 'Public gardens',
    area: 'Alcantara / Prazeres',
    description: 'A quieter green escape for longer offline moments.',
    activity: 'Long walk',
    suggestion: 'Agree on one phone-free loop before sitting down.',
    score: 4,
    coordinates: { lat: 38.7075, lng: -9.1778 },
  },
  {
    id: 'principe-real',
    name: 'Jardim do Principe Real',
    type: 'Public gardens',
    area: 'Principe Real',
    description: 'A central garden that works well for quick meetups and decompression.',
    activity: 'Short meetup',
    suggestion: 'Put phones face down while you catch up.',
    score: 4,
    coordinates: { lat: 38.7159, lng: -9.1484 },
  },
  {
    id: 'amalia',
    name: 'Jardim Amalia Rodrigues',
    type: 'Public gardens',
    area: 'Marques de Pombal / Sao Sebastiao',
    description: 'A clean, open garden close to campus and transport routes.',
    activity: 'Post-class reset',
    suggestion: 'Replace a scroll break with a ten-minute walk.',
    score: 4,
    coordinates: { lat: 38.7304, lng: -9.1533 },
  },
  {
    id: 'eduardo',
    name: 'Parque Eduardo VII',
    type: 'Parks & gardens',
    area: 'Marques de Pombal',
    description: 'Open space, long views and easy movement through the city.',
    activity: 'Walk',
    suggestion: 'Replace scrolling with movement.',
    score: 4,
    coordinates: { lat: 38.7288, lng: -9.1526 },
  },
  {
    id: 'campo-grande',
    name: 'Jardim do Campo Grande',
    type: 'Parks & gardens',
    area: 'Campo Grande',
    description: 'A student-friendly meeting spot near university areas.',
    activity: 'Meet near school/university areas',
    suggestion: 'Good for students in Lisbon.',
    score: 4,
    coordinates: { lat: 38.7564, lng: -9.1574 },
  },
  {
    id: 'monsanto',
    name: 'Parque Florestal de Monsanto',
    type: 'Parks & gardens',
    area: 'Monsanto',
    description: 'A larger green area for real movement and longer offline plans.',
    activity: 'Walk, run or picnic',
    suggestion: 'Choose a meeting point and leave phones silent.',
    score: 5,
    coordinates: { lat: 38.7265, lng: -9.1852 },
  },
  {
    id: 'ribeirinho-oriente',
    name: 'Jardim Ribeirinho Oriente',
    type: 'Public gardens',
    area: 'Parque das Nacoes',
    description: 'A riverside route with space for walking, talking and slowing down.',
    activity: 'Riverside walk',
    suggestion: 'Walk to the next landmark before checking your phone.',
    score: 4,
    coordinates: { lat: 38.7633, lng: -9.0926 },
  },
  {
    id: 'ccb',
    name: 'CCB / Belem area',
    type: 'Cultural spaces',
    area: 'Belem',
    description: 'A clean cultural route for a slow walk and conversation.',
    activity: 'Walk, talk, culture',
    suggestion: 'Explore without scrolling.',
    score: 5,
    coordinates: { lat: 38.6958, lng: -9.2094 },
  },
  {
    id: 'parque-tejo',
    name: 'Parque Tejo',
    type: 'Parks & gardens',
    area: 'Parque das Nacoes',
    description: 'A wide riverside park for longer walks, group meetups and open-air resets.',
    activity: 'Riverside reset',
    suggestion: 'Walk together until the lock timer ends.',
    score: 4,
    coordinates: { lat: 38.7826, lng: -9.0929 },
  },
  {
    id: 'orlando-ribeiro',
    name: 'Biblioteca Orlando Ribeiro',
    type: 'Libraries',
    area: 'Telheiras',
    description: 'A calm public library with good focus energy for study blocks.',
    activity: 'Study block',
    suggestion: 'Use a table session as a phone-free focus sprint.',
    score: 4,
    coordinates: { lat: 38.7602, lng: -9.1673 },
  },
  {
    id: 'lx-factory',
    name: 'LX Factory area',
    type: 'Cultural spaces',
    area: 'Alcantara',
    description: 'A lively creative area that works well for planned offline meetups.',
    activity: 'Coffee, bookshops or short walk',
    suggestion: 'Choose the plan before arriving and keep phones away.',
    score: 3,
    coordinates: { lat: 38.7033, lng: -9.1787 },
  },
  {
    id: 'saldanha-cafes',
    name: 'Saldanha study cafe area',
    type: 'Cafes',
    area: 'Saldanha',
    description: 'A central area with practical cafe options for short study sprints and low-pressure meetups.',
    activity: 'Study cafe sprint',
    suggestion: 'Pick one cafe and agree on a phone-free study sprint.',
    score: 3,
    coordinates: { lat: 38.7358, lng: -9.145 },
  },
  {
    id: 'chiado-cafes',
    name: 'Chiado quiet cafe area',
    type: 'Cafes',
    area: 'Chiado',
    description: 'A walkable meeting area with calmer cafe corners for quick phone-free catch-ups.',
    activity: 'Quiet catch-up',
    suggestion: 'Choose a table and keep phones away while you talk.',
    score: 3,
    coordinates: { lat: 38.7107, lng: -9.1425 },
  },
];

export const setupSteps = [
  'Open Shortcuts.',
  'Tap Automation.',
  'Create a new personal automation.',
  'Choose App.',
  'Select one app, like TikTok or Instagram.',
  'Choose When Opened.',
  'Add action Open URL.',
  'Paste the direct LoopOut URL for that app.',
  'Add the one-time bypass check if you want to return to the app from LoopOut.',
  'Choose Run Immediately if available.',
  'Repeat with each distracting app you want to connect.',
];

export const weeklySaved = [18, 24, 12, 35, 22, 42, 27];
export const sessionsByApp = [
  { label: 'Instagram', value: 38 },
  { label: 'TikTok', value: 25 },
  { label: 'YouTube', value: 18 },
  { label: 'X', value: 10 },
];

export const groupRewardTiers = [
  { size: 1, label: '1 person offline', reward: '10% off', discountPercent: 10 },
  { size: 2, label: '2 people offline', reward: '15% off', discountPercent: 15 },
  { size: 3, label: '3+ people offline', reward: '20% off or shared item', discountPercent: 20 },
];

export const partnerPlaces = [
  {
    id: 'offline-cafe-saldanha',
    name: 'LoopOut Cafe Saldanha',
    type: 'Cafe',
    city: 'Lisbon',
    area: 'Saldanha',
    address: 'Saldanha, Lisbon',
    description: 'A calm seed partner concept for quick offline coffee breaks after a LoopOut session.',
    score: 5,
    isVerified: true,
    isSeedPartner: true,
    coordinates: { lat: 38.7358, lng: -9.145 },
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Saldanha,Lisbon',
    tags: ['Coffee', 'Students', 'Quiet hours'],
  },
  {
    id: 'blue-table-chiado',
    name: 'Blue Table Chiado',
    type: 'Cafe',
    city: 'Lisbon',
    area: 'Chiado',
    address: 'Chiado, Lisbon',
    description: 'A premium cafe concept for phone-free catch-ups and short creative breaks.',
    score: 4,
    isVerified: true,
    isSeedPartner: true,
    coordinates: { lat: 38.7107, lng: -9.1425 },
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Chiado,Lisbon',
    tags: ['Coffee', 'Conversation', 'Central'],
  },
  {
    id: 'study-corner-alvalade',
    name: 'Study Corner Alvalade',
    type: 'Study Space',
    city: 'Lisbon',
    area: 'Alvalade',
    address: 'Alvalade, Lisbon',
    description: 'A study cafe concept for students who want a quiet reward after focused app use.',
    score: 5,
    isVerified: true,
    isSeedPartner: true,
    coordinates: { lat: 38.7521, lng: -9.1432 },
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Alvalade,Lisbon',
    tags: ['Study', 'Menu', 'Focus'],
  },
  {
    id: 'belem-social-spot',
    name: 'Belem Social Spot',
    type: 'Cafe',
    city: 'Lisbon',
    area: 'Belem',
    address: 'Belem, Lisbon',
    description: 'A social cafe concept for small groups that want to meet without the scroll.',
    score: 4,
    isVerified: true,
    isSeedPartner: true,
    coordinates: { lat: 38.6958, lng: -9.2094 },
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Belem,Lisbon',
    tags: ['Group', 'Walkable', 'Culture'],
  },
  {
    id: 'campo-grande-coffee',
    name: 'Offline Coffee Campo Grande',
    type: 'Cafe',
    city: 'Lisbon',
    area: 'Campo Grande',
    address: 'Campo Grande, Lisbon',
    description: 'A student-friendly coffee concept near campus routes and gardens.',
    score: 4,
    isVerified: true,
    isSeedPartner: true,
    coordinates: { lat: 38.7564, lng: -9.1574 },
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Campo+Grande,Lisbon',
    tags: ['Students', 'Upgrade', 'Near park'],
  },
  {
    id: 'estrela-quiet-cafe',
    name: 'Estrela Quiet Cafe',
    type: 'Cafe',
    city: 'Lisbon',
    area: 'Estrela',
    address: 'Estrela, Lisbon',
    description: 'A quieter cafe concept for post-walk conversations near Jardim da Estrela.',
    score: 4,
    isVerified: false,
    isSeedPartner: true,
    coordinates: { lat: 38.7138, lng: -9.1604 },
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Estrela,Lisbon',
    tags: ['Candidate', 'Garden nearby'],
  },
  {
    id: 'marvila-study-house',
    name: 'Marvila Study House',
    type: 'Study Space',
    city: 'Lisbon',
    area: 'Marvila',
    address: 'Marvila, Lisbon',
    description: 'A study-space concept for focused groups and quiet work sessions.',
    score: 4,
    isVerified: false,
    isSeedPartner: true,
    coordinates: { lat: 38.746, lng: -9.1052 },
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Marvila,Lisbon',
    tags: ['Candidate', 'Study'],
  },
  {
    id: 'principe-real-talk-spot',
    name: 'Principe Real Talk Spot',
    type: 'Restaurant',
    city: 'Lisbon',
    area: 'Principe Real',
    address: 'Principe Real, Lisbon',
    description: 'A restaurant concept for relaxed, phone-light social plans.',
    score: 4,
    isVerified: false,
    isSeedPartner: true,
    coordinates: { lat: 38.7159, lng: -9.1484 },
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Principe+Real,Lisbon',
    tags: ['Candidate', 'Dinner'],
  },
];

export const rewardCampaigns = [
  {
    id: 'reward-saldanha-15-drinks',
    partnerPlaceId: 'offline-cafe-saldanha',
    title: '15% off drinks',
    description: 'Valid while your LoopOut lock is active.',
    rewardType: 'percentage_discount',
    discountPercent: 15,
    minimumGroupSize: 1,
    groupBoost: true,
    terms: [
      'One use per user per day.',
      'Valid only during an active LoopOut lock.',
      'Cannot be combined with other offers.',
      'Staff must scan or enter the code before purchase.',
    ],
    validWindow: 'Today while your lock is active',
    status: 'active',
  },
  {
    id: 'reward-chiado-cookie',
    partnerPlaceId: 'blue-table-chiado',
    title: 'Free cookie with coffee',
    description: 'Get a free cookie when you buy a coffee during your offline break.',
    rewardType: 'free_item',
    freeItemName: 'Cookie',
    minimumGroupSize: 1,
    groupBoost: false,
    terms: ['One use per user per day.', 'Coffee purchase required.', 'Valid during active lock time.'],
    validWindow: 'Today while your lock is active',
    status: 'active',
  },
  {
    id: 'reward-alvalade-study-20',
    partnerPlaceId: 'study-corner-alvalade',
    title: '20% off study menu',
    description: 'A study reward for users who stay offline during focused work.',
    rewardType: 'percentage_discount',
    discountPercent: 20,
    minimumGroupSize: 1,
    groupBoost: true,
    terms: ['Valid on study menu items.', 'Staff may ask to see active lock screen.', 'Not valid after pass expiry.'],
    validWindow: 'School days, 12:00-18:00',
    status: 'active',
  },
  {
    id: 'reward-belem-group',
    partnerPlaceId: 'belem-social-spot',
    title: 'Group discount',
    description: 'Invite friends who are also offline and unlock a better group reward.',
    rewardType: 'group_reward',
    discountPercent: 10,
    minimumGroupSize: 2,
    groupBoost: true,
    terms: ['At least 2 locked LoopOut users for group reward.', 'One group redemption per visit.', 'Valid during active lock time.'],
    validWindow: 'Today while your lock is active',
    status: 'active',
  },
  {
    id: 'reward-campo-upgrade',
    partnerPlaceId: 'campo-grande-coffee',
    title: 'Free size upgrade',
    description: 'Upgrade one drink size when you redeem your LoopOut Pass.',
    rewardType: 'upgrade',
    minimumGroupSize: 1,
    groupBoost: false,
    terms: ['One drink upgrade per user.', 'Valid during active lock time.', 'Cannot be combined with happy hour.'],
    validWindow: 'Today while your lock is active',
    status: 'active',
  },
];

export const demoProfile = {
  id: 'demo-user-bernardo',
  name: 'Bernardo Allen',
  email: 'bernardo@loopout.demo',
  username: 'bernardo',
  city: 'Lisbon',
  area: 'Saldanha',
  avatar: 'BA',
};

export const demoFriends = [
  {
    id: 'demo-friend-sofia',
    name: 'Sofia Martins',
    avatar: 'SM',
    status: 'Offline now',
    area: 'Chiado',
    available: true,
    isOffline: true,
    lockedApp: 'Instagram',
    remainingMinutes: 18,
    email: 'sofia@loopout.demo',
    username: 'sofia',
  },
  {
    id: 'demo-friend-tomas',
    name: 'Tomas Ribeiro',
    avatar: 'TR',
    status: 'Free in 20 min',
    area: 'Saldanha',
    available: true,
    isOffline: true,
    lockedApp: 'TikTok',
    remainingMinutes: 20,
    email: 'tomas@loopout.demo',
    username: 'tomas',
  },
  {
    id: 'demo-friend-ines',
    name: 'Ines Costa',
    avatar: 'IC',
    status: 'Planning later',
    area: 'Alvalade',
    available: false,
    isOffline: false,
    lockedApp: '',
    remainingMinutes: 0,
    email: 'ines@loopout.demo',
    username: 'ines',
  },
  {
    id: 'demo-friend-miguel',
    name: 'Miguel Santos',
    avatar: 'MS',
    status: 'Available to meet',
    area: 'Belem',
    available: true,
    isOffline: true,
    lockedApp: 'YouTube Shorts',
    remainingMinutes: 24,
    email: 'miguel@loopout.demo',
    username: 'miguel',
  },
];

export const demoContactMatches = [
  { id: 'contact-maria', name: 'Maria Lopes', handle: '@maria', match: 'Uses LoopOut weekly' },
  { id: 'contact-francisco', name: 'Francisco Neves', handle: '@francisco', match: '2 mutual friends' },
  { id: 'contact-rita', name: 'Rita Almeida', handle: '@rita', match: 'Ready for phone-free coffee' },
];

export const demoEvents = [
  {
    id: 'event-coffee-saldanha',
    title: 'Phone-free coffee meetup',
    host: 'LoopOut Cafe Saldanha',
    location: 'Saldanha',
    time: 'Today, 17:30',
    category: 'Coffee meetup',
    reward: '15% off drinks',
    attendees: 18,
  },
  {
    id: 'event-gulbenkian-walk',
    title: 'Walk in Gulbenkian Gardens',
    host: 'LoopOut Community',
    location: 'Gulbenkian',
    time: 'Saturday, 11:00',
    category: 'Walk',
    reward: 'Group boost eligible',
    attendees: 32,
  },
  {
    id: 'event-campus-focus',
    title: 'Campus focus challenge',
    host: 'Lisbon International School',
    location: 'Library',
    time: 'Monday, 09:15',
    category: 'Campus challenge',
    reward: 'Digital wellbeing badge',
    attendees: 124,
  },
];

export const demoNotifications = [
  { id: 'note-lock', title: 'Lock started', body: 'Instagram is protected for 24 min.', type: 'personal' },
  { id: 'note-pass', title: 'LoopOut Pass earned', body: '15% off is active at LoopOut Cafe Saldanha.', type: 'reward' },
  { id: 'note-invite', title: 'Sofia invited you offline', body: 'Chiado quiet cafe area, today at 17:30.', type: 'friends' },
  { id: 'note-class', title: 'Classroom focus started', body: '11B Economics has 21 of 24 students active.', type: 'education' },
];

export const demoProgressStats = {
  completedSessions: 12,
  totalIntentionalMinutes: 184,
  totalLockMinutes: 310,
  mostUsedApp: 'Instagram',
  mostCommonPurpose: 'reply',
  weeklySaved: [28, 42, 35, 58, 46, 62, 39],
  currentStreak: 5,
  invitesSent: 8,
  invitesAccepted: 4,
  estimatedTimeSaved: 310,
  sessionsByApp: [
    { label: 'Instagram', value: 42 },
    { label: 'TikTok', value: 26 },
    { label: 'YouTube', value: 18 },
    { label: 'Snapchat', value: 14 },
  ],
  today: {
    completedSessions: 3,
    intentionalMinutes: 38,
    lockMinutes: 72,
  },
};

export const demoBusinessMetrics = {
  qrScans: 428,
  rewardsRedeemed: 176,
  invalidScans: 21,
  groupVisits: 64,
  repeatVisitors: 42,
  estimatedCustomers: 238,
  estimatedRevenue: '€3.8k',
  activeCampaigns: 5,
  upcomingEvents: 3,
  bestCampaign: '20% off for groups of 3+',
  bestTime: '15:00-18:00',
  scansOverTime: [28, 46, 39, 68, 74, 92, 81],
  campaignSplit: [
    ['10% off', 38],
    ['Group reward', 27],
    ['Free cookie', 19],
    ['Upgrade', 16],
  ],
};

export const demoEducation = {
  institution: 'Lisbon International School',
  teachers: ['Prof. Sofia Almeida', 'Prof. Joao Martins', 'Prof. Clara Costa'],
  classes: ['11B Economics', '10A English', '12C Study Hall'],
  rooms: ['Room 2.1', 'Room 3.4', 'Library', 'Auditorium'],
  activeSession: {
    id: 'edu-focus-11b',
    className: '11B Economics',
    subject: 'Economics',
    room: 'Room 2.1',
    teacher: 'Prof. Sofia Almeida',
    time: '09:15-10:45',
    startedAtLabel: '09:15',
    endsAtLabel: '10:45',
    durationMinutes: 90,
    elapsedMinutes: 28,
    remainingMinutes: 62,
    blockedApps: ['TikTok', 'Instagram', 'Snapchat', 'YouTube Shorts'],
    allowedApps: ['Calculator', 'Dictionary'],
    strictness: 'Guided',
    note: 'Focus without taking phones away.',
    studentsActive: 4,
    studentsTotal: 5,
    publicCode: 'CLASS-11B-FOCUS',
  },
  studentStatuses: [
    { id: 'seat-01', name: 'Leonor P.', status: 'Scanned', scanned: true, joinedAt: '09:16', remaining: '62 min' },
    { id: 'seat-02', name: 'Duarte M.', status: 'Scanned', scanned: true, joinedAt: '09:15', remaining: '62 min' },
    { id: 'seat-03', name: 'Marta S.', status: 'Scanned late', scanned: true, joinedAt: '09:24', remaining: '62 min' },
    { id: 'seat-04', name: 'Afonso R.', status: 'Not scanned', scanned: false, joinedAt: '-', remaining: '-' },
    { id: 'seat-05', name: 'Beatriz C.', status: 'Scanned', scanned: true, joinedAt: '09:15', remaining: '62 min' },
  ],
  schedules: [
    { title: 'Economics A', time: 'Monday 09:15-10:45', room: 'Room 2.1', rule: 'Focus Mode' },
    { title: 'Study Hall', time: 'Weekdays 14:00-16:00', room: 'Library', rule: 'Voluntary focus' },
    { title: 'Library Focus', time: '08:00-18:00', room: 'Library', rule: 'QR study rooms' },
    { title: 'Exam Mode', time: 'Custom dates', room: 'Auditorium', rule: 'Strict classroom session' },
  ],
  seminars: [
    { title: 'Social media and mental health', audience: 'Students', date: 'Oct 14', speaker: 'LoopOut Wellbeing Team', status: 'Scheduled', score: '4.8/5' },
    { title: 'Sleep and screen time', audience: 'Parents', date: 'Nov 04', speaker: 'Guest psychologist', status: 'Planning', score: '-' },
    { title: 'Focus and study habits', audience: 'Teachers', date: 'Nov 21', speaker: 'Prof. Clara Costa', status: 'Scheduled', score: '4.7/5' },
  ],
  certificate: {
    name: 'LoopOut Digital Wellbeing Partner',
    status: 'Pilot approved',
    issueDate: 'Sep 12',
    renewalDate: 'Next semester',
    requirements: [
      'Classroom focus pilot',
      'Student digital wellbeing seminar',
      'Teacher onboarding session',
      'Basic privacy policy',
      'Student feedback survey',
      'Semester report',
    ],
  },
};

export const pricingPlans = [
  {
    line: 'Personal',
    plans: [
      { name: 'Free', price: '€0', features: ['Purpose timer', 'Simulated lock', 'Limited friends', 'Public places'] },
      { name: 'Premium', price: '€4.99/mo', features: ['Advanced analytics', 'Friend groups', 'Exclusive rewards', 'Unlimited sessions'] },
    ],
  },
  {
    line: 'Business',
    plans: [
      { name: 'Free Pilot', price: '€0', features: ['Basic listing', 'Limited campaigns', 'Limited scans'] },
      { name: 'Partner', price: '€49/mo', features: ['Verified listing', 'QR rewards', 'Analytics', 'Events'] },
      { name: 'Featured', price: 'Custom', features: ['Priority placement', 'Promoted campaigns', 'Advanced insights'] },
    ],
  },
  {
    line: 'Education',
    plans: [
      { name: 'Basic', price: 'Pilot', features: ['Teacher dashboards', 'Classroom QR sessions', 'Basic reports'] },
      { name: 'Plus', price: 'Annual', features: ['School dashboard', 'Certificate', 'One seminar per semester'] },
      { name: 'Premium', price: 'Custom', features: ['Parent workshops', 'Teacher training', 'Campus events', 'Priority support'] },
    ],
  },
];
